/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, clang */
/* Command for C compiler:
   clang -c -w -O3  -I/usr/lib/nim -o /home/kozak/Devel/D/Trash/source/nimcache/hashes.o /home/kozak/Devel/D/Trash/source/nimcache/hashes.c */
#define NIM_INTBITS 64
#include "nimbase.h"
NIM_EXTERNC N_NOINLINE(void, HEX00_hashesInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, HEX00_hashesDatInit)(void) {
}

