/* Generated by Nim Compiler v0.10.2 */
/*   (c) 2014 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, clang */
/* Command for C compiler:
   clang -c -w -O3  -I/usr/lib/nim -o /home/kozak/Devel/D/Trash/source/nimcache/tables.o /home/kozak/Devel/D/Trash/source/nimcache/tables.c */
#define NIM_INTBITS 64
#include "nimbase.h"
typedef struct table136178 table136178;
typedef struct keyvaluepairseq136181 keyvaluepairseq136181;
typedef struct keyvaluepair136184 keyvaluepair136184;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct keyvaluepair136184 {
NU8 Field0;
NI Field1;
NI Field2;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  table136178  {
keyvaluepairseq136181* Data;
NI Counter;
};
typedef N_NIMCALL_PTR(void, TY3089) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3094) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3089 marker;
TY3094 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct keyvaluepairseq136181 {
  TGenericSeq Sup;
  keyvaluepair136184 data[SEQ_DECL_SIZE];
};
N_NIMCALL(NI, rawget_136866)(table136178 t_136873, NI key_136876);
static N_INLINE(NI, hash_98804)(NI x);
static N_INLINE(NI, nexttry_108409)(NI h, NI maxhash);
N_NIMCALL(void, TMP37)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(NIM_BOOL, mustrehash_108302)(NI length, NI counter);
N_NIMCALL(void, enlarge_136585)(table136178* t_136594);
N_NIMCALL(void, rawinsert_136655)(table136178* t_136664, keyvaluepairseq136181** data_136672, NI key_136676, NI val_136678);
TNimType NTI136184; /* KeyValuePair */
TNimType NTI108009; /* SlotEnum */
extern TNimType NTI108; /* int */
TNimType NTI136181; /* KeyValuePairSeq */

static N_INLINE(NI, hash_98804)(NI x) {
	NI result;
	result = 0;
	result = x;
	return result;
}

static N_INLINE(NI, nexttry_108409)(NI h, NI maxhash) {
	NI result;
	result = 0;
	result = (NI)((NI64)((NI64)(5 * h) + 1) & maxhash);
	return result;
}

N_NIMCALL(NI, rawget_136866)(table136178 t_136873, NI key_136876) {
	NI result;
	NI h;
	NI LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = hash_98804(key_136876);
	h = (NI)(LOC1 & (t_136873.Data->Sup.len-1));
	{
		while (1) {
			if (!!((t_136873.Data->data[h].Field0 == ((NU8) 0)))) goto LA3;
			{
				NIM_BOOL LOC6;
				LOC6 = 0;
				LOC6 = (t_136873.Data->data[h].Field1 == key_136876);
				if (!(LOC6)) goto LA7;
				LOC6 = (t_136873.Data->data[h].Field0 == ((NU8) 1));
				LA7: ;
				if (!LOC6) goto LA8;
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			h = nexttry_108409(h, (t_136873.Data->Sup.len-1));
		} LA3: ;
	}
	result = -1;
	BeforeRet: ;
	return result;
}

N_NIMCALL(NI, HEX5BHEX5D_136852)(table136178 t_136859, NI key_136862) {
	NI result;
	NI index;
	result = 0;
	index = rawget_136866(t_136859, key_136862);
	{
		if (!(0 <= index)) goto LA3;
		result = t_136859.Data->data[index].Field2;
	}
	LA3: ;
	return result;
}
N_NIMCALL(void, TMP37)(void* p, NI op) {
	keyvaluepairseq136181* a;
	NI LOC1;
	a = (keyvaluepairseq136181*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}

N_NIMCALL(void, inittable_136205)(NI initialsize_136210, table136178* Result) {
	(*Result).Counter = 0;
	unsureAsgnRef((void**) (&(*Result).Data), (keyvaluepairseq136181*) newSeq((&NTI136181), initialsize_136210));
}

static N_INLINE(NIM_BOOL, mustrehash_108302)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	result = 0;
	LOC1 = 0;
	LOC1 = ((NI64)(length * 2) < (NI64)(counter * 3));
	if (LOC1) goto LA2;
	LOC1 = ((NI64)(length - counter) < 4);
	LA2: ;
	result = LOC1;
	return result;
}

N_NIMCALL(void, rawinsert_136655)(table136178* t_136664, keyvaluepairseq136181** data_136672, NI key_136676, NI val_136678) {
	NI h;
	NI LOC1;
	LOC1 = 0;
	LOC1 = hash_98804(key_136676);
	h = (NI)(LOC1 & ((*data_136672)->Sup.len-1));
	{
		while (1) {
			if (!((*data_136672)->data[h].Field0 == ((NU8) 1))) goto LA3;
			h = nexttry_108409(h, ((*data_136672)->Sup.len-1));
		} LA3: ;
	}
	(*data_136672)->data[h].Field1 = key_136676;
	(*data_136672)->data[h].Field2 = val_136678;
	(*data_136672)->data[h].Field0 = ((NU8) 1);
}

N_NIMCALL(void, enlarge_136585)(table136178* t_136594) {
	keyvaluepairseq136181* n;
	keyvaluepairseq136181* LOC8;
	n = 0;
	n = (keyvaluepairseq136181*) newSeq((&NTI136181), (NI64)((*t_136594).Data->Sup.len * 2));
	{
		NI i_136640;
		NI HEX3Atmp_136719;
		NI res_136722;
		i_136640 = 0;
		HEX3Atmp_136719 = 0;
		HEX3Atmp_136719 = ((*t_136594).Data->Sup.len-1);
		res_136722 = 0;
		{
			while (1) {
				if (!(res_136722 <= HEX3Atmp_136719)) goto LA3;
				i_136640 = res_136722;
				{
					if (!((*t_136594).Data->data[i_136640].Field0 == ((NU8) 1))) goto LA6;
					rawinsert_136655(t_136594, (&n), (*t_136594).Data->data[i_136640].Field1, (*t_136594).Data->data[i_136640].Field2);
				}
				LA6: ;
				res_136722 += 1;
			} LA3: ;
		}
	}
	LOC8 = 0;
	LOC8 = (*t_136594).Data;
	unsureAsgnRef((void**) (&(*t_136594).Data), n);
	n = LOC8;
}

N_NIMCALL(void, add_136555)(table136178* t_136564, NI key_136568, NI val_136570) {
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = mustrehash_108302((*t_136564).Data->Sup.len, (*t_136564).Counter);
		if (!LOC3) goto LA4;
		enlarge_136585(t_136564);
	}
	LA4: ;
	rawinsert_136655(t_136564, (&(*t_136564).Data), key_136568, val_136570);
	(*t_136564).Counter += 1;
}
NIM_EXTERNC N_NOINLINE(void, HEX00_tablesInit)(void) {
}

NIM_EXTERNC N_NOINLINE(void, HEX00_tablesDatInit)(void) {
static TNimNode* TMP33[3];
static TNimNode* TMP34[3];
NI TMP36;
static char* NIM_CONST TMP35[3] = {
"seEmpty", 
"seFilled", 
"seDeleted"};
static TNimNode TMP5[8];
NTI136184.size = sizeof(keyvaluepair136184);
NTI136184.kind = 18;
NTI136184.base = 0;
NTI136184.flags = 3;
TMP33[0] = &TMP5[1];
NTI108009.size = sizeof(NU8);
NTI108009.kind = 14;
NTI108009.base = 0;
NTI108009.flags = 3;
for (TMP36 = 0; TMP36 < 3; TMP36++) {
TMP5[TMP36+2].kind = 1;
TMP5[TMP36+2].offset = TMP36;
TMP5[TMP36+2].name = TMP35[TMP36];
TMP34[TMP36] = &TMP5[TMP36+2];
}
TMP5[5].len = 3; TMP5[5].kind = 2; TMP5[5].sons = &TMP34[0];
NTI108009.node = &TMP5[5];
TMP5[1].kind = 1;
TMP5[1].offset = offsetof(keyvaluepair136184, Field0);
TMP5[1].typ = (&NTI108009);
TMP5[1].name = "Field0";
TMP33[1] = &TMP5[6];
TMP5[6].kind = 1;
TMP5[6].offset = offsetof(keyvaluepair136184, Field1);
TMP5[6].typ = (&NTI108);
TMP5[6].name = "Field1";
TMP33[2] = &TMP5[7];
TMP5[7].kind = 1;
TMP5[7].offset = offsetof(keyvaluepair136184, Field2);
TMP5[7].typ = (&NTI108);
TMP5[7].name = "Field2";
TMP5[0].len = 3; TMP5[0].kind = 2; TMP5[0].sons = &TMP33[0];
NTI136184.node = &TMP5[0];
NTI136181.size = sizeof(keyvaluepairseq136181*);
NTI136181.kind = 24;
NTI136181.base = (&NTI136184);
NTI136181.flags = 2;
NTI136181.marker = TMP37;
}

